<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Librería NumPy</font> </center>




NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [1]:
import numpy as np


NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [2]:
l1 = [1,2,3,4]
l1

[1, 2, 3, 4]

In [4]:
a = np.array(l1)
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(4,)

In [10]:
m1 = np.array([[[1,2,3],
          [2,3,4],
          [5,6,7]]])

In [11]:
m1.shape

(1, 3, 3)

## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [22]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
x = np.linspace(0,100)

In [26]:
# f(x) = x**2 + 3x
def f(x):
    return x**2 + 3*x

In [27]:
f(x)

array([0.00000000e+00, 1.02873803e+01, 2.89046231e+01, 5.58517284e+01,
       9.11286964e+01, 1.34735527e+02, 1.86672220e+02, 2.46938776e+02,
       3.15535194e+02, 3.92461474e+02, 4.77717618e+02, 5.71303623e+02,
       6.73219492e+02, 7.83465223e+02, 9.02040816e+02, 1.02894627e+03,
       1.16418159e+03, 1.30774677e+03, 1.45964182e+03, 1.61986672e+03,
       1.78842149e+03, 1.96530612e+03, 2.15052062e+03, 2.34406497e+03,
       2.54593919e+03, 2.75614327e+03, 2.97467722e+03, 3.20154102e+03,
       3.43673469e+03, 3.68025823e+03, 3.93211162e+03, 4.19229488e+03,
       4.46080800e+03, 4.73765098e+03, 5.02282382e+03, 5.31632653e+03,
       5.61815910e+03, 5.92832153e+03, 6.24681383e+03, 6.57363599e+03,
       6.90878800e+03, 7.25226989e+03, 7.60408163e+03, 7.96422324e+03,
       8.33269471e+03, 8.70949604e+03, 9.09462724e+03, 9.48808830e+03,
       9.88987922e+03, 1.03000000e+04])

In [ ]:
#plot(x,f(x))

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [33]:
np.random.rand(100)

array([0.28280534, 0.97898806, 0.69454854, 0.97751897, 0.18009925,
       0.94619252, 0.17719156, 0.92890556, 0.16047566, 0.7651594 ,
       0.98776031, 0.00640722, 0.90474631, 0.19444017, 0.5063066 ,
       0.79457447, 0.51233639, 0.28047077, 0.1134612 , 0.34546903,
       0.28668344, 0.91621681, 0.27291872, 0.37774295, 0.28752496,
       0.15776628, 0.0522883 , 0.32121228, 0.8346322 , 0.64925683,
       0.93901815, 0.13097563, 0.84274055, 0.1463218 , 0.97819694,
       0.2837422 , 0.53000827, 0.43193366, 0.62713462, 0.18605919,
       0.17642028, 0.2327988 , 0.72324745, 0.53705912, 0.45525945,
       0.27361479, 0.68960725, 0.64492742, 0.42749577, 0.59630534,
       0.4761324 , 0.27280848, 0.21308154, 0.95072145, 0.38182928,
       0.6322431 , 0.74562968, 0.40593704, 0.40706419, 0.7358268 ,
       0.89263864, 0.02933393, 0.1617486 , 0.68469213, 0.04781908,
       0.64727396, 0.34100708, 0.61177841, 0.73102649, 0.09996184,
       0.37829532, 0.35860384, 0.52590686, 0.26162274, 0.55001

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [34]:
np.random.rand(10)

array([0.8785067 , 0.55690268, 0.7939196 , 0.7080035 , 0.70550836,
       0.65917236, 0.27589751, 0.32051738, 0.74720982, 0.34335506])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [35]:
np.random.randint(1,100,10)

array([88, 10, 59, 36, 56, 74, 85, 26,  1, 65])

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [36]:
np.random.seed(5)

In [38]:
np.random.rand()

0.8707323061773764

In [40]:
np.random.seed(5)
np.random.rand()

0.22199317108973948

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [49]:
arr.max(), arr.min()

(24, 0)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.argmax()

24

In [52]:
arr.argmin()

0

## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [53]:
arr.shape

(25,)

### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [54]:
arr.dtype

dtype('int32')

In [55]:
type(arr)

numpy.ndarray

In [56]:
l = [1, 'ss', help, [1,2]]
l

[1,
 'ss',
 Type help() for interactive help, or help(object) for help about object.,
 [1, 2]]