
<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Operaciones con NumPy</font> </center>



## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [4]:
import numpy as np

In [1]:
l1 = [1,1,2,3]
l2 = [2,2,3,4]


In [2]:
l1 + l2

[1, 1, 2, 3, 2, 2, 3, 4]

In [5]:
a1 = np.array(l1)
a2 = np.array(l2)

In [6]:
a1 + a2

array([3, 3, 5, 7])

In [7]:
a1 - a2

array([-1, -1, -1, -1])

In [8]:
2*a1

array([2, 2, 4, 6])

In [9]:
2*a2 + 3*a1

array([ 7,  7, 12, 17])

In [11]:
a1.transpose()

array([1, 1, 2, 3])

In [12]:
a1@a2

22

In [ ]:
# Crear una matriz aleatoria de números enteros de dimensión 4x2 -> A
# Crear una matriz aleatoria de números enteros de dimensión 2x6 -> B
# Realizar la multiplicación de Matrices C = A*B
# Realizar la multiplicación de Matrices C = B*A



In [13]:
A = np.random.randint(100, size=(4,2))
A

array([[25, 13],
       [46, 67],
       [95, 85],
       [27, 57]])

In [15]:
B = np.random.randint(100, size=(2,6))
B

array([[45, 39,  5, 30, 38, 56],
       [60,  1, 20, 14, 73, 92]])

In [16]:
A.shape

(4, 2)

In [17]:
B.shape

(2, 6)

In [18]:
A@B

array([[ 1905,   988,   385,   932,  1899,  2596],
       [ 6090,  1861,  1570,  2318,  6639,  8740],
       [ 9375,  3790,  2175,  4040,  9815, 13140],
       [ 4635,  1110,  1275,  1608,  5187,  6756]])

In [19]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

In [20]:
np.dot(A,B)

array([[ 1905,   988,   385,   932,  1899,  2596],
       [ 6090,  1861,  1570,  2318,  6639,  8740],
       [ 9375,  3790,  2175,  4040,  9815, 13140],
       [ 4635,  1110,  1275,  1608,  5187,  6756]])

In [21]:
np.dot(B,A)

ValueError: shapes (2,6) and (4,2) not aligned: 6 (dim 1) != 4 (dim 0)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [23]:
np.sqrt(a1)

array([1.        , 1.        , 1.41421356, 1.73205081])

In [24]:
np.exp(a1)

array([ 2.71828183,  2.71828183,  7.3890561 , 20.08553692])

In [25]:
np.sin(a1)

array([0.84147098, 0.84147098, 0.90929743, 0.14112001])

In [26]:
np.cos(a1)

array([ 0.54030231,  0.54030231, -0.41614684, -0.9899925 ])

In [27]:
np.log(a1)

array([0.        , 0.        , 0.69314718, 1.09861229])

In [28]:
np.min(a1)

1

In [29]:
np.max(a1)

3

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [30]:
a1.sum()

7

In [31]:
a1.std()

0.82915619758885

In [32]:
a1.var()

0.6875

In [33]:
a1.mean()

1.75

In [34]:
A.sum()

415

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [35]:
A.shape

(4, 2)

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='Figures/axis_logic.png' width=400/>

In [37]:
A.sum(axis=0)

array([193, 222])

In [38]:
A.sum(axis=1)

array([ 38, 113, 180,  84])

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

## Ejercicio 1


### Numpy

1. Crear un vector con valores de 10 a 49.
2. Elevar al cuadrado a aquellos números divisibles por 3.
3. Redimensionar ese vector en una matriz de 20x2.
4. Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

In [39]:
#1.- Crear un vector con valores de 10 a 49
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [40]:
#2.- Elevar al cuadrado a aquellos números divisibles por 3.

for i in range(len(a)):
    if a[i]%3==0:
        print(a[i]**2)

144
225
324
441
576
729
900
1089
1296
1521
1764
2025
2304


In [44]:
a[a%3==0]**2

array([ 144,  225,  324,  441,  576,  729,  900, 1089, 1296, 1521, 1764,
       2025, 2304])

In [46]:
#3.- Redimensionar ese vector en una matriz de 20x2.
a2 = np.arange(40)
a2.shape

(40,)

In [47]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [49]:
mat1 = a2.reshape(20,2)

In [51]:
#Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
mat2 = np.random.randint(100, size=(2,10))
mat2

array([[60, 32, 58, 34, 79, 90, 22, 48, 26, 60],
       [44,  3, 95, 35, 26, 33, 76, 50, 58, 81]])

In [52]:
mat1@mat2

array([[  44,    3,   95,   35,   26,   33,   76,   50,   58,   81],
       [ 252,   73,  401,  173,  236,  279,  272,  246,  226,  363],
       [ 460,  143,  707,  311,  446,  525,  468,  442,  394,  645],
       [ 668,  213, 1013,  449,  656,  771,  664,  638,  562,  927],
       [ 876,  283, 1319,  587,  866, 1017,  860,  834,  730, 1209],
       [1084,  353, 1625,  725, 1076, 1263, 1056, 1030,  898, 1491],
       [1292,  423, 1931,  863, 1286, 1509, 1252, 1226, 1066, 1773],
       [1500,  493, 2237, 1001, 1496, 1755, 1448, 1422, 1234, 2055],
       [1708,  563, 2543, 1139, 1706, 2001, 1644, 1618, 1402, 2337],
       [1916,  633, 2849, 1277, 1916, 2247, 1840, 1814, 1570, 2619],
       [2124,  703, 3155, 1415, 2126, 2493, 2036, 2010, 1738, 2901],
       [2332,  773, 3461, 1553, 2336, 2739, 2232, 2206, 1906, 3183],
       [2540,  843, 3767, 1691, 2546, 2985, 2428, 2402, 2074, 3465],
       [2748,  913, 4073, 1829, 2756, 3231, 2624, 2598, 2242, 3747],
       [2956,  983, 4379, 1967, 29

In [54]:
mat1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [53]:
#Obtener la transpuesta de la matriz resultante.
mat1.transpose()

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39]])

In [55]:
mat1.T

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39]])

## Ejercicio 2

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68, 70, 71, 73]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menor imc al que tiene mayor imc.