<img style="float: left;;" src='Figures/alinco.png'/></a>

# <center> <font color= #000047> Ejercicios Numpy 




<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400px" height="400px" />



¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [2]:
# Crear dos vectores
x = [4,5,8,-2,3]
y = [3,1,-7,-9,5]

In [3]:
# Suma de vectores
x+y

[4, 5, 8, -2, 3, 3, 1, -7, -9, 5]

In [4]:
suma = [x[i] + y[i] for i in range(len(x))]
suma

[7, 6, 1, -11, 8]

In [ ]:
# ¿con ciclos quizá?
s=[]
for i in range(len(x)):
    s.append(x[i] + y[i])

In [5]:
# Producto por escalar
x

[4, 5, 8, -2, 3]

In [7]:
5*x

[4,
 5,
 8,
 -2,
 3,
 4,
 5,
 8,
 -2,
 3,
 4,
 5,
 8,
 -2,
 3,
 4,
 5,
 8,
 -2,
 3,
 4,
 5,
 8,
 -2,
 3]

In [ ]:
# ¿con ciclos quizá?


### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

Para nuestra fortuna, NumPy ya viene instalado por defecto en la instalación de Anaconda.

Así que si queremos empezar a utilizarlo, lo único que debemos hacer es importarlo:

In [8]:
# Importar numpy
import numpy as np

Lo que acabamos de hacer es un procedimiento genérico para importar librerías:
- se comienza con la palabra clave `import`;
- a continuación el nombre de la librería, en este caso `numpy`;
- opcionalmente se puede incluir una cláusula `as` y una abreviación del nombre de la librería. Para el caso de NumPy, la comunidad comúmente usa la abreviación `np`.

Ahora, intentemos hacer lo mismo que que antes, pero con el arreglo n-dimensional que provee NumPy como vector:

In [9]:
# Ayuda sobre arreglo N-dimensional
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, etc.).
  

In [ ]:
# Crear dos vectores


In [ ]:
# Suma de vectores


In [ ]:
# Producto interno


### Diferencias fundamentales entre Listas de Python y Arreglos de NumPy

Mientras que las listas y los arreglos tienen algunas similaridades (ambos son colecciones ordenadas de valores), existen ciertas diferencias abismales entre este tipo de estructuras de datos:

- A diferencia de las listas, todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos (esto es, todos enteros, o flotantes, o strings, etc).

- Por lo anterior, los arreglos de NumPy soportan operaciones aritméticas y otras funciones matemáticas que se ejecutan en cada elemento del arreglo. Las listas no soportan estos cálculos.

- Los arreglos de NumPy tienen dimensionalidad.

## 1.1 Funciones de NumPy

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

Antes que nada, definamos las variables que nos dan:

In [10]:
# Definir numero de contenedores, medida minima y medida maxima
n_contenedores = 5
medida_min = 5
medida_max = 25


A continuación, generaremos un arreglo de números enteros aleatorios entre 5 y 25 cm que representarán los radios y las alturas de los cilindros:

In [13]:
# Ayuda de np.random.randint()
# Números aleatorios que representan radios y alturas.
# Inicializar la semilla

medidas = np.random.randint(medida_min, medida_max, size=(10,))
# Ver valores
medidas

array([20,  7,  6, 11, 10, 22, 22, 10, 24, 15])

In [14]:
medidas = medidas.reshape((2,5))
medidas

array([[20,  7,  6, 11, 10],
       [22, 22, 10, 24, 15]])

De los números generados, separemos los que corresponden a los radios, y los que corresponden a las alturas:

In [15]:
# Radios
radios = medidas[0,:] 
radios

array([20,  7,  6, 11, 10])

In [16]:
# Alturas
alturas = medidas[1,:]
alturas

array([22, 22, 10, 24, 15])

1. Con lo anterior, calculemos cada uno los volúmenes:

$V_c = \pi * r^2 * h$

In [17]:
np.pi

3.141592653589793

In [18]:
radios**2

array([400,  49,  36, 121, 100])

In [20]:
# Volúmenes de los contenedores
volumenes = np.pi*(radios**2)*alturas
volumenes

array([27646.01535159,  3386.63688057,  1130.97335529,  9123.18506602,
        4712.38898038])

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Symbol_great.svg" width="400px" height="400px" />

### ¡Excelente!

Con esta línea de código tan sencilla, pudimos obtener de un solo jalón todos los volúmenes de nuestros contenedores.

Esta es la potencia que nos ofrece NumPy. Podemos operar los arreglos de forma rápida, sencilla, y muy eficiente.

In [23]:
volumenes

array([27646.01535159,  3386.63688057,  1130.97335529,  9123.18506602,
        4712.38898038])

2. Ahora, el volumen total

In [24]:
# Volumen total
volumenes.sum()

45999.199633861754

3. ¿Cuál contenedor puede almacenar más volumen? ¿Cuánto?

In [ ]:
# Contenedor que puede almacenar más volumen


In [25]:
# Volumen máximo
volumenes.max()

27646.01535159018

In [26]:
volumenes == volumenes.max()

array([ True, False, False, False, False])

In [27]:
volumenes.argmax()

0

In [ ]:
# También se puede, pero no es recomendable. Ver comparación de tiempos


4. ¿Cuál contenedor puede almacenar menos volumen? ¿Cuánto?

In [28]:
# Contenedor que puede almacenar menos volumen
volumenes.min()

1130.9733552923256

In [29]:
# Volumen mínimo
volumenes.argmin()

2

5. Media, mediana y desviación estándar de los volúmenes

In [30]:
# Media, mediana y desviación estándar
volumenes.mean()

9199.83992677235

In [31]:
volumenes.std()


9584.408350772534

In [33]:
np.median(volumenes)

4712.38898038469

In [ ]:
[1,2,3,4,5,6,7,8]

## 1.2 Trabajando con matrices

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

Lo primero será generar los números del 1 al 25. ¿Cómo podemos hacer esto?

np.arange = np.array(range)

In [34]:
# Ayuda en la función np.arange()
cartas = np.arange(1,26)
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
# Números del 1 al 25
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

Luego, tal y como en un juego de cartas, deberíamos barajarlos, antes de repartirlos:

In [36]:
# Ayuda en la función np.random.shuffle()
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)

    Modify a sequence in-place by shuffling its contents.

    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.

    .. note::
        New code should use the `~numpy.random.Generator.shuffle`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.

    Returns
    -------
    None

    See Also
    --------
    random.Generator.shuffle: which should be used for new code.

    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random

    Multi-dimensional arrays are only shuffled along the first axis:

 

In [38]:
# Barajar
np.random.shuffle(cartas)

In [39]:
# Ver valores
cartas

array([ 4, 11, 18, 14,  8, 16, 25, 17, 13,  2,  3,  6,  7, 21,  1, 10, 19,
        9, 15, 22, 23, 24, 12,  5, 20])

Bien. Ahora, deberíamos distribuir las cartas. Podemos imaginarnos la distribución como una matriz 5x5:

In [41]:
# Repartir cartas
cartas = cartas.reshape((5,5))
cartas


array([[ 4, 11, 18, 14,  8],
       [16, 25, 17, 13,  2],
       [ 3,  6,  7, 21,  1],
       [10, 19,  9, 15, 22],
       [23, 24, 12,  5, 20]])

In [42]:
# Ver valores
cartas

array([[ 4, 11, 18, 14,  8],
       [16, 25, 17, 13,  2],
       [ 3,  6,  7, 21,  1],
       [10, 19,  9, 15, 22],
       [23, 24, 12,  5, 20]])

Entonces, tenemos 5 cartas para cada una de las 5 personas, visualizadas como una matriz 5x5.

Lo único que nos falta es encontrar la suma para cada uno, es decir, sumar el elemento de la diagonal principal y restar las demás entradas de la fila (o columna).

¿Cómo hacemos esto?

In [43]:
# Ayuda en la función np.eye()
I5 = np.eye(5)
I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# Matriz con la diagonal principal
I5*cartas

array([[ 4.,  0.,  0.,  0.,  0.],
       [ 0., 25.,  0.,  0.,  0.],
       [ 0.,  0.,  7.,  0.,  0.],
       [ 0.,  0.,  0., 15.,  0.],
       [ 0.,  0.,  0.,  0., 20.]])

In [47]:
# Ayuda en la función np.ones()
complemento = np.ones((5,5)) - I5
complemento

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [48]:
# Matriz con los elementos fuera de la diagonal negativos
complemento*cartas

array([[ 0., 11., 18., 14.,  8.],
       [16.,  0., 17., 13.,  2.],
       [ 3.,  6.,  0., 21.,  1.],
       [10., 19.,  9.,  0., 22.],
       [23., 24., 12.,  5.,  0.]])

In [50]:
mat_para_suma = I5*cartas - complemento*cartas
mat_para_suma


array([[  4., -11., -18., -14.,  -8.],
       [-16.,  25., -17., -13.,  -2.],
       [ -3.,  -6.,   7., -21.,  -1.],
       [-10., -19.,  -9.,  15., -22.],
       [-23., -24., -12.,  -5.,  20.]])

In [51]:
mat_para_suma.sum(axis=0)


array([-48., -35., -49., -38., -13.])

In [52]:
mat_para_suma.sum(axis=1)

array([-47., -23., -24., -45., -44.])

In [54]:
mat_para_suma[0,:].sum()

-47.0

In [ ]:
# Matriz completa


In [55]:
# Sumar por filas
resultado = mat_para_suma.sum(axis=1)
resultado


array([-47., -23., -24., -45., -44.])

¿Quién es el ganador?

In [56]:
resultado.max()

-23.0

In [57]:
resultado.argmax()

1