
<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Operaciones con NumPy</font> </center>



## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [1]:
import numpy as np

l1 = [1,2,3,4]
l2 = [13,5,3,4]

In [ ]:
# Crear una matriz aleatoria de números enteros de dimensión 4x2 -> A
# Crear una matriz aleatoria de números enteros de dimensión 2x6 -> B
# Realizar la multiplicación de Matrices C = A*B
# Realizar la multiplicación de Matrices C = B*A



In [2]:
a1 = np.array(l1)
a2 = np.array(l2)

In [3]:
a1 + a2

array([14,  7,  6,  8])

In [4]:
a1 - a2

array([-12,  -3,   0,   0])

In [5]:
a1.transpose()

array([1, 2, 3, 4])

In [6]:
a1@a2

np.int64(48)

In [9]:
A = np.random.randint(100, size=(4,2))
A

array([[92, 26],
       [ 2, 29],
       [91, 15],
       [32, 73]], dtype=int32)

In [15]:
B = np.random.randint(100, size=(2,6))

In [16]:
A.shape

(4, 2)

In [17]:
B.shape

(2, 6)

In [18]:
A@B

array([[1616, 6860, 8420, 3522, 9568, 1274],
       [1400, 2822, 1946, 1413, 1516, 1421],
       [1084, 5778, 7664, 2980, 8971,  735],
       [3632, 8398, 6894, 4231, 6270, 3577]], dtype=int32)

In [19]:
np.dot(A,B)

array([[1616, 6860, 8420, 3522, 9568, 1274],
       [1400, 2822, 1946, 1413, 1516, 1421],
       [1084, 5778, 7664, 2980, 8971,  735],
       [3632, 8398, 6894, 4231, 6270, 3577]], dtype=int32)

In [20]:
np.dot(B,A)

ValueError: shapes (2,6) and (4,2) not aligned: 6 (dim 1) != 4 (dim 0)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [21]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [22]:
a1.sum()

np.int64(10)

In [23]:
a1.std()

np.float64(1.118033988749895)

In [24]:
a1.var()

np.float64(1.25)

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [25]:
A.shape

(4, 2)

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='Figures/axis_logic.png' width=400/>

In [26]:
A.sum(axis=0)

array([217, 143])

In [27]:
A.sum(axis=1)

array([118,  31, 106, 105])

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

## Ejercicio 1


### Numpy

1. Crear un vector con valores de 10 a 49.
2. Elevar al cuadrado a aquellos números divisibles por 3.
3. Redimensionar ese vector en una matriz de 20x2.
4. Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

In [ ]:
#1.- Crear un vector con valores de 10 a 49

In [29]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
#2.-Elevar al cuadrado a aquellos numeros divisibles por 3
for i in range (len(a)):
    if a[i]%3==0:
        print(a[i]**2)

144
225
324
441
576
729
900
1089
1296
1521
1764
2025
2304


In [32]:
#3.-Redimensionar ese vector en una matriz de 20x2
a2 = np.arange(40)
a2.shape

(40,)

In [45]:
a2.reshape(20,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [44]:
#4. Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
mat2 = np.random.randint(100, size=(20,2))
mat2

array([[93, 51],
       [13, 34],
       [81,  1],
       [79, 33],
       [ 1,  3],
       [36, 85],
       [33, 61],
       [ 4,  4],
       [72, 33],
       [55, 43],
       [36, 90],
       [11,  4],
       [34, 19],
       [69, 87],
       [ 8, 95],
       [24, 74],
       [82, 37],
       [99, 72],
       [52, 84],
       [ 8, 24]], dtype=int32)

In [46]:
mat2@a2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 40 is different from 2)

In [47]:
mat2.transpose()

array([[93, 13, 81, 79,  1, 36, 33,  4, 72, 55, 36, 11, 34, 69,  8, 24,
        82, 99, 52,  8],
       [51, 34,  1, 33,  3, 85, 61,  4, 33, 43, 90,  4, 19, 87, 95, 74,
        37, 72, 84, 24]], dtype=int32)

## Ejercicio 2

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [50]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68, 70, 71, 73]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menorimc al que tiene mayor imc.