
<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Actividad 1: librería NumPy y Pandas.</font>
___




Ahora que hemos hecho el repaso de la líbreria de NumPy, es momento de probar los conocimientos adquiridos. 

<div class="alert alert-danger" style="margin: 10px"><strong>NOTA IMPORTANTE!</strong> Asegúrese de no escribir código en las celdas donde se muestra ejemplificada la salida (etiquetada como "no escribir aquí") <br> de lo contrario, terminará reescribiendo la salida esperada.</div>

#### 1. importar NumPy como np

In [1]:
# CÓDIGO AQUÍ
import numpy as np

#### 2. Crear un arreglo de ceros de tamaño 10 

In [ ]:
# CÓDIGO AQUÍ


In [2]:
# NO ESCRIBIR AQUÍ

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Crear un arreglo de unos de tamaño 10 

In [ ]:
# CÓDIGO AQUÍ


In [3]:
# NO ESCRIBIR AQUÍ

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Crear un arreglo de cincos de tamaño 10 

In [ ]:
# CÓDIGO AQUÍ


In [4]:
# NO ESCRIBIR AQUÍ

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Crear un arreglo de enteros que contenga elementos del 10 al 50

In [ ]:
# CÓDIGO AQUÍ


In [5]:
# NO ESCRIBIR AQUÍ

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Crear un arreglo de todos los enteros pares en el intervalo de 10 a 50

In [ ]:
# CÓDIGO AQUÍ


In [6]:
# NO ESCRIBIR AQUÍ

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Crear una matriz de 3x3 con valores en el rango de 0 a 8.

In [ ]:
# CÓDIGO AQUÍ


In [7]:
# NO ESCRIBIR AQUÍ

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Crear una matriz identidad de 3x3

In [ ]:
# CÓDIGO AQUÍ


In [8]:
# NO ESCRIBIR AQUÍ

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Usa NumPy para generar un número aleatorio entre 0 y 1 <br><br>&emsp;NOTA: Tu resultado puede ser diferente al que se muestra en el resultado de ejemplo.

In [ ]:
# CÓDIGO AQUÍ


In [9]:
# NO ESCRIBIR AQUÍ

array([0.65248055])

#### 10. Usa NumPy para generar un arreglo que contenga 25 números aleatorios muestreados a partir de una distribución normal estándar.<br><br>&emsp;&ensp;NOTA: Los valores de su resultado pueden ser diferentes de los que se muestran en el resultado de ejemplo.

In [ ]:
# CÓDIGO AQUÍ


In [10]:
# NO ESCRIBIR AQUÍ

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Crea la matriz que se muestra en la salida de ejemplo:

In [ ]:
# CÓDIGO AQUÍ


In [11]:
# NO ESCRIBIR AQUÍ

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Crea una matriz de tamaño 20 linealmente espaciada en el intervalo de 0 a 1:

In [ ]:
# CÓDIGO AQUÍ


In [12]:
# NO ESCRIBIR AQUÍ

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexación y Selección en Numpy 

Ahora se le dará una matriz inicial (¡asegúrese de ejecutar la celda a continuación!) Y se le pedirá que replique las salidas de la matriz que se muestra en la salida de ejemplo:


In [7]:
# EJECUTAR ESTA CELDA. ES NUESTRA MATRIZ DE INICIO
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Escriba código que reproduzca el resultado que se muestra a continuación.<br><br>&emsp;&ensp;Tenga cuidado de no ejecutar la celda inmediatamente arriba de la salida (etiquetada como: "NO ESCRIBIR AQUI"), de lo contrario no podrá ver el resultado de la salida.

In [ ]:
# CÓDIGO AQUÍ
mat2 = mat[2:,1:]

In [14]:
# NO ESCRIBIR AQUÍ

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Utilizando el resultado anterior escriba código que reproduzca el resultado que se muestra a continuación.

In [ ]:
# CÓDIGO AQUÍ


In [15]:
# NO ESCRIBIR AQUÍ

20

#### 15. Utilizando el resultado de Out[14] Escriba código que reproduzca el resultado que se muestra a continuación.

In [ ]:
# CÓDIGO AQUÍ
mat3 = mat2[:,0] -10
mat = mat2.reshape(3,1)

In [16]:
# NO ESCRIBIR AQUÍ

array([[ 2],
       [ 7],
       [12]])

#### 16. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [ ]:
# CÓDIGO AQUÍ


In [17]:
# NO ESCRIBIR AQUÍ

array([21, 22, 23, 24, 25])

#### 17. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [ ]:
# CÓDIGO AQUÍ


In [18]:
# NO ESCRIBIR AQUÍ

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Operaciones con NumPy

#### 18. Obtenga la suma de todos los valores en mat

In [ ]:
# CÓDIGO AQUÍ


In [19]:
# NO ESCRIBIR AQUÍ

325

#### 19. Obtenga la desviación estándar de todos los valores en mat.

In [ ]:
# CÓDIGO AQUÍ


In [20]:
# NO ESCRIBIR AQUÍ

7.211102550927978

#### 20. Obtenga la suma de todas las columnas en mat

In [ ]:
# CÓDIGO AQUÍ


In [21]:
# NO ESCRIBIR AQUÍ

array([55, 60, 65, 70, 75])

## Operaciones con Pandas

**21. importar la librería de pandas**

In [24]:
# código aquí

**22. Lea el archivo bank.csv que se encuentra en la carpeta raíz. ¡Presta mucha atención a la ubicación del archivo .csv!.**

In [ ]:
# código aquí

**23. Mustre las primero 5 filas del dataset**

In [ ]:
# código aquí

**24. Calcule el promedio de la edad de las personas del dataset**

In [ ]:
# código aquí

**25. ¿Cuál es el status marital de la persona más joven en el dataset?**



In [52]:
# código aquí

**26. ¿Cuántas categorías de trabajos únicos existen en el dataset?**

In [57]:
# código aquí

**27. Muestre cuántas personas hay por categoría de trabajo**

In [20]:
# código aquí

**28. ¿Cuál es el porcentaje de las personas en el dataset que están casadas?**

In [22]:
# código aquí

**29. En el dataset existe una columna etiquetada como: "default". Use el comando .map() para crear una nueva columna llamada "default_code" que contenga el valor 0 si el valor de la columna es "no", o 1 si el valor en la columna esta etiquetada como "si". Muestre los 5 primeros valores de esta nueva columna**


In [ ]:
# código aquí

**30. Usando el método pandas .apply (), cree una nueva columna llamada "marital_code". Esta columna solo contendrá un código abreviado de la posible primera letra del estado civil. (Por ejemplo, "m" para "casado", "s" para "soltero", etc.**

In [ ]:
# código aquí

**31. ¿Cuál fue el trabajp con duración más larga?**

In [ ]:
# código aquí

**32. ¿Cuál es el nivel de educación más común para las personas que están desempleadas?**

In [ ]:
# código aquí

**33. ¿Cuál es la edad promedio para estar desempleado?**

In [45]:
# código aquí